name: dbt_employee_details
version: '1.0'
profile: employee_details_profile

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]

models:
  dbt_employee_details:
    staging:
      +materialized: view
    curation:
      +materialized: incremental