employee_details_profile:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: gcp-de-batch-sim-464816-476514
      dataset: Employee_Details_cur
      threads: 4
      timeout_seconds: 300
      location: US
      priority: interactive